// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: src/proto/federation.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "federation";

export interface GetClientFederationRequest {
  clientId: string;
}

export interface GetClientResponse {
  clientUrl: string;
  hash: string;
  salt: string;
}

export interface Federation {
  name: string;
  clientId: string;
}

export interface GetAllFederationResponse {
  federations: Federation[];
}

export interface CreateRequest {
  name: string;
  clientUrl: string;
  userId: string;
}

export interface CreateFederationResponse {
  name: string;
  clientId: string;
  clientUrl: string;
  isActivated: boolean;
  id: string;
}

export interface FederationResponse {
  status: boolean;
  message: string;
}

export interface UpdateRequest {
  name: string;
  clientUrl: string;
  userId: string;
  clientId: string;
  isActivated: boolean;
}

export interface FederationRequest {
  userId: string;
  clientId: string;
}

export interface NewSecretResponse {
  secret: string;
}

export interface GetAllFederationRequest {
  userId: string;
}

export interface GetFederationResponse {
  name: string;
  clientId: string;
  clientUrl: string;
  isActivated: boolean;
  id: string;
}

export const FEDERATION_PACKAGE_NAME = "federation";

export interface FederationProxyServiceClient {
  create(request: CreateRequest, metadata?: Metadata): Observable<CreateFederationResponse>;

  update(request: UpdateRequest, metadata?: Metadata): Observable<CreateFederationResponse>;

  newSecret(request: FederationRequest, metadata?: Metadata): Observable<NewSecretResponse>;

  toggle(request: FederationRequest, metadata?: Metadata): Observable<FederationResponse>;

  remove(request: FederationRequest, metadata?: Metadata): Observable<FederationResponse>;

  get(request: FederationRequest, metadata?: Metadata): Observable<GetFederationResponse>;

  getAll(request: GetAllFederationRequest, metadata?: Metadata): Observable<GetAllFederationResponse>;

  getClient(request: GetClientFederationRequest, metadata?: Metadata): Observable<GetClientResponse>;
}

export interface FederationProxyServiceController {
  create(
    request: CreateRequest,
    metadata?: Metadata,
  ): Promise<CreateFederationResponse> | Observable<CreateFederationResponse> | CreateFederationResponse;

  update(
    request: UpdateRequest,
    metadata?: Metadata,
  ): Promise<CreateFederationResponse> | Observable<CreateFederationResponse> | CreateFederationResponse;

  newSecret(
    request: FederationRequest,
    metadata?: Metadata,
  ): Promise<NewSecretResponse> | Observable<NewSecretResponse> | NewSecretResponse;

  toggle(
    request: FederationRequest,
    metadata?: Metadata,
  ): Promise<FederationResponse> | Observable<FederationResponse> | FederationResponse;

  remove(
    request: FederationRequest,
    metadata?: Metadata,
  ): Promise<FederationResponse> | Observable<FederationResponse> | FederationResponse;

  get(
    request: FederationRequest,
    metadata?: Metadata,
  ): Promise<GetFederationResponse> | Observable<GetFederationResponse> | GetFederationResponse;

  getAll(
    request: GetAllFederationRequest,
    metadata?: Metadata,
  ): Promise<GetAllFederationResponse> | Observable<GetAllFederationResponse> | GetAllFederationResponse;

  getClient(
    request: GetClientFederationRequest,
    metadata?: Metadata,
  ): Promise<GetClientResponse> | Observable<GetClientResponse> | GetClientResponse;
}

export function FederationProxyServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["create", "update", "newSecret", "toggle", "remove", "get", "getAll", "getClient"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("FederationProxyService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("FederationProxyService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const FEDERATION_PROXY_SERVICE_NAME = "FederationProxyService";
