// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: src/proto/login.proto

/* eslint-disable */
import type { Metadata } from '@grpc/grpc-js';
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'login';

export interface LoginRequest {
  email: string;
  password: string;
}

export interface LoginResponse {
  success: boolean;
  message: string;
  phone?: string | undefined;
  is2fa?: boolean | undefined;
  userId?: string | undefined;
}

export interface LoginStatusRequest {
  userId: string;
}

export interface LoginStatusResponse {
  message?: string | undefined;
  userStatus?: UserStatus | undefined;
}

export interface UserStatus {
  admin: boolean;
  email: string;
  isAdaptive: boolean;
  is2fa: boolean;
}

export const LOGIN_PACKAGE_NAME = 'login';

export interface LoginProxyServiceClient {
  login(request: LoginRequest, metadata?: Metadata): Observable<LoginResponse>;

  getLoginStatus(
    request: LoginStatusRequest,
    metadata?: Metadata,
  ): Observable<LoginStatusResponse>;
}

export interface LoginProxyServiceController {
  login(
    request: LoginRequest,
    metadata?: Metadata,
  ): Promise<LoginResponse> | Observable<LoginResponse> | LoginResponse;

  getLoginStatus(
    request: LoginStatusRequest,
    metadata?: Metadata,
  ):
    | Promise<LoginStatusResponse>
    | Observable<LoginStatusResponse>
    | LoginStatusResponse;
}

export function LoginProxyServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['login', 'getLoginStatus'];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('LoginProxyService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('LoginProxyService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const LOGIN_PROXY_SERVICE_NAME = 'LoginProxyService';
