// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: src/proto/user.proto

/* eslint-disable */
import type { Metadata } from '@grpc/grpc-js';
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'user';

export interface CreateUserRequest {
  email: string;
  phone: string;
  password: string;
}

export interface CreateSocialUserRequest {
  email: string;
  provider: string;
  providerId: string;
}

export interface UserResponse {
  id: string;
  email: string;
  phone: string;
}

export interface SocialUserResponse {
  id: string;
  email: string;
}

export interface CheckExistRequest {
  email: string;
}

export interface CheckExistResponse {
  exist: boolean;
}

export interface FindUserByIdRequest {
  id: string;
}

export interface FindUserRequest {
  email: string;
}

export const USER_PACKAGE_NAME = 'user';

export interface UserProxyServiceClient {
  createUser(
    request: CreateUserRequest,
    metadata?: Metadata,
  ): Observable<UserResponse>;

  createSocialUser(
    request: CreateSocialUserRequest,
    metadata?: Metadata,
  ): Observable<SocialUserResponse>;

  checkExist(
    request: CheckExistRequest,
    metadata?: Metadata,
  ): Observable<CheckExistResponse>;

  findUserById(
    request: FindUserByIdRequest,
    metadata?: Metadata,
  ): Observable<UserResponse>;

  findUser(
    request: FindUserRequest,
    metadata?: Metadata,
  ): Observable<UserResponse>;
}

export interface UserProxyServiceController {
  createUser(
    request: CreateUserRequest,
    metadata?: Metadata,
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  createSocialUser(
    request: CreateSocialUserRequest,
    metadata?: Metadata,
  ):
    | Promise<SocialUserResponse>
    | Observable<SocialUserResponse>
    | SocialUserResponse;

  checkExist(
    request: CheckExistRequest,
    metadata?: Metadata,
  ):
    | Promise<CheckExistResponse>
    | Observable<CheckExistResponse>
    | CheckExistResponse;

  findUserById(
    request: FindUserByIdRequest,
    metadata?: Metadata,
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  findUser(
    request: FindUserRequest,
    metadata?: Metadata,
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;
}

export function UserProxyServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'createUser',
      'createSocialUser',
      'checkExist',
      'findUserById',
      'findUser',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('UserProxyService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('UserProxyService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const USER_PROXY_SERVICE_NAME = 'UserProxyService';
