// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: src/proto/verify-code.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "verifyMfa";

export interface VerifyMfaRequest {
  email: string;
}

export interface VerifyMfaResponse {
  userId: string;
}

export const VERIFY_MFA_PACKAGE_NAME = "verifyMfa";

export interface VerifyMfaProxyServiceClient {
  getUserId(request: VerifyMfaRequest, metadata?: Metadata): Observable<VerifyMfaResponse>;
}

export interface VerifyMfaProxyServiceController {
  getUserId(
    request: VerifyMfaRequest,
    metadata?: Metadata,
  ): Promise<VerifyMfaResponse> | Observable<VerifyMfaResponse> | VerifyMfaResponse;
}

export function VerifyMfaProxyServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getUserId"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("VerifyMfaProxyService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("VerifyMfaProxyService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const VERIFY_MFA_PROXY_SERVICE_NAME = "VerifyMfaProxyService";
